### ISSUE TITLE
Creating form elements.

### ISSUE THREAD

**Issue by Leepee** [txusballesteros/welcome-coordinator#9]
Thanks for the lib, it looks great. Trying to use it at the moment, but how do you do the interactive parts such as here: https://github.com/txusballesteros/welcome-coordinator/blob/master/assets/onboarding_demo.gif ?

It's not in the example program, and when I add objects such as editTexts, it's scrolling to the next page automatically. Are there any tips or example programs I could see? I'd love to get it working right!

Many thanks,

Lee Davison

**Comment by txusballesteros** [comment]
Hi @Leepee,

I sorry, but that demo is a part of Redbooth App and that's not on this repository. :'(
